<?php

declare(strict_types=1);

use LPWork\Console\Output;
use LPWork\Emitters\ConsoleEmitter;
use LPWork\Responses\ConsoleResponse;
use Tests\support\console\OutputStreams;

it('emits console responses to stdout and stderr', function (): void {
    $streams = OutputStreams::create();
    $emitter = new ConsoleEmitter(new Output($streams->stdout, $streams->stderr));

    $exitCode = $emitter->emit(ConsoleResponse::output(
        stdout: "Hello\n",
        stderr: 'Careful',
        exitCode: 7,
    ));

    expect($exitCode)->toBe(7)
        ->and($streams->stdout())->toBe("Hello\n")
        ->and($streams->stderr())->toBe("Careful\n");
});

it('emits console response callbacks', function (): void {
    $streams = OutputStreams::create();
    $emitter = new ConsoleEmitter(new Output($streams->stdout, $streams->stderr));

    $exitCode = $emitter->emit(ConsoleResponse::using(static function (Output $output): int {
        $output->writeln('Generated by callback');

        return 3;
    }));

    expect($exitCode)->toBe(3)
        ->and($streams->stdout())->toBe("Generated by callback\n")
        ->and($streams->stderr())->toBe('');
});
